### ISSUE TITLE
include download links for already-built versions of the extension(s)

### ISSUE THREAD

**Issue by omouse** [propublica/facebook-political-ads#10]
wondering if there's an already-built version of this for Firefox and Chrome that I could install without cloning the repo and building the project?

**Comment by varner** [comment]
There's a build for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/facebook-ad-collector/) and [Chrome](https://chrome.google.com/webstore/detail/facebook-political-ad-col/enliecaalhkhhihcmnbjfmmjkljlcinl?hl=en)

**Comment by thejefflarson** [comment]
Yeah, anyone wanna open a pull request to add that to the README?

**Comment by varner** [comment]
just did!

**Comment by omouse** [comment]
@varner lol opened a PR just now too! think your [PR](https://github.com/propublica/facebook-political-ads/pull/11) beat me by a minute?

**Comment by thejefflarson** [comment]
You guys are my heros! I’ll merge them both momentarily.
