### ISSUE TITLE
MutationObserver steals focus from Facebook messenger?

### ISSUE THREAD

**Issue by dreisman** [propublica/facebook-political-ads#3]
Needs investigation. With extension running and an active FB messenger chat window open, the main page will steal focus from the chat window. 

Minor nit, but if it is actually caused by the extension it is a fairly annoying usability issue. Turning off the extension seems to have fixed the issue for me...

To reproduce:
Type message into FB messenger chat popup at bottom of FB page. After ~10 seconds of typing, focus will no longer be in the chat window and you have to click to place the cursor in the chat window to keep typing.

**Comment by peterk** [comment]
Maybe still a bug. If typing in a messenger popup, the cursor will intermittently be reset to the beginning of the message field. This is annoying as your messenger text will be garbled.

**Comment by jeremybmerrill** [comment]
Hi @peterk:

I'm working to see if I can fix the Messenger issue, but first, I'm trying to replicate the issue. Can you tell me if you're using Firefox or Chrome? 

When the bug occurs and your cursor is reset to the beginning of the field, are you actively typing? Are you actively scrolling down the page?

Thanks!

**Comment by peterk** [comment]
Using Chrome 64 (on Mac). Cursor reset happens when typing. Not sure if it happens without typing. Not scrolling. Using messenger popup in regular facebook feed page.

**Comment by peterk** [comment]
Reset to beginning of field happens also when not typing actively in the field.
