### ISSUE TITLE
Sidebar ads not detected when FB UI language is swedish

### ISSUE THREAD

**Issue by peterk** [propublica/facebook-political-ads#36]
Looking at the code it seems like sidebar ad collecting was implemented but I do not see sidebar ads in the classifier when using Facebook in Swedish. Switching it to English and sidebar ads are detected/collected properly.

**Comment by jeremybmerrill** [comment]
@Rukicc Ah, makes sense. Can you tell me what it says in Latvian in the same place where it says "Sponsored" in English, in this screenshot?
<img width="518" alt="screenshot 2018-06-26 10 28 46" src="https://user-images.githubusercontent.com/548250/41919128-c25d0f1a-792b-11e8-86cf-3051f8578f23.png">

**Comment by Rukicc** [comment]
Hi,

If i select this String and  paste in notepad it look like: "Apma A ksāt A
a rek A lāma"


Corect String to find is "Apmaksāta reklāma"

Arnis


On Tue, Jun 26, 2018 at 5:29 PM, Jeremy B. Merrill <notifications@github.com

**Comment by jeremybmerrill** [comment]
@Rukicc thank you!

**Comment by jeremybmerrill** [comment]
I'm uploading the new version that supports "Apmaksāta reklāma" right now, it should be available within a few hours (and will be updated automatically).
