### ISSUE TITLE
Classification Option: «I don't know»

### ISSUE THREAD

**Issue by tpreusse** [propublica/facebook-political-ads#40]
A user here in Switzerland reported back that it would be great to have an «I don't know» option when classifying ads.

This especially make sense in a Swiss context because you can easily end up seeing ads in another national language that you might not understand.

This could be implemented as a local only thing—only dismissing the ad from the classifying queue. On the other hand this could be counter productive if many users use it and one might want to monitor that (by reporting to the server).

What do you think? Does it make sense in other contexts too? Spanish ads in the US? I'd be happy to work on the client side.

**Comment by thejefflarson** [comment]
Yeah, I don't think I want to go down this road. I'd rather that people make a choice than ignore an ad.
