### ISSUE TITLE
"Sponsored" label in popup mangled with additional "S" characters

### ISSUE THREAD

**Issue by peterk** [propublica/facebook-political-ads#46]
A minor issue I guess but the ads displayed in the collector popup has an extra "S" character inserted every two chars in the "sponsored" label.

![image](https://user-images.githubusercontent.com/19284/37021899-7caa8162-2121-11e8-8d92-04bdc5b528e1.png)

**Comment by thejefflarson** [comment]
Fixed with: https://github.com/propublica/facebook-political-ads/commit/ed6ec1731a7617daded8c3e71d95eac852b91d58#diff-8e80f67927ef3ef89e1cbcfb55b103c0 -- should auto update.
