### ISSUE TITLE
Popup note fully displayed sometimes

### ISSUE THREAD

**Issue by peterk** [propublica/facebook-political-ads#47]
Sometimes the popup does not display fully:

![image](https://user-images.githubusercontent.com/19284/37031138-ef3cefbe-213d-11e8-8315-c981fe19a556.png)

Re-clicking it typically helps. Started appearing recently in Chrome 64.0.3282.186.

**Comment by thejefflarson** [comment]
Yeah, we fixed it here: https://github.com/propublica/facebook-political-ads/commit/a407af1bf9a6b7d638767e770f066dacfbc75830
