### ISSUE TITLE
Jest complaining about missing key

### ISSUE THREAD

**Issue by thejefflarson** [propublica/facebook-political-ads#55]
When I run the jest tests I get a warning about a missing key in groupedattrs:

      console.error node_modules/react/node_modules/fbjs/lib/warning.js:33
      Warning: Each child in an array or iterator should have a unique "key" prop.
      Check the top-level render call using <tbody>. See https://fb.me/react-warning-keys for more information.
          in tr

@jeremybmerrill wanna take a look?

**Comment by jeremybmerrill** [comment]
a little bit of skew between the code and the tests; fixed
