### ISSUE TITLE
Want to bring it to Brazil!

### ISSUE THREAD

**Issue by pmarkun** [propublica/facebook-political-ads#63]
Hey Folks!

We at the LabHacker in Brazil wants to bring this tool to the national elections.
Should we deploy another instance and another plugin? Or there is some way to access and process the data within ProPublica implementation afterwards? :)

**Comment by thejefflarson** [comment]
Go ahead and send an email to adcollector@propublica.org and we can get you
set up. It is better not to fork the project so there’s only one database
of information.

—Jeff
