### ISSUE TITLE
Did the ad collector stop working with the new update of Chrome (v66)?

### ISSUE THREAD

**Issue by peterk** [propublica/facebook-political-ads#68]
I get no ads detected as of yesterday when I updated Chrome to version 66. Running with Swedish language settings. If there is a simple way to debug detection I would be happy to help out.

**Comment by peterk** [comment]
Looking into it I think Facebook may have changed some of the class names for ad html which means the query selector don't match ads anymore. Tried both swedish and english language setting (in FB) and no ads are detected.

**Comment by jeremybmerrill** [comment]
You were right, I think, as discussed via email. Fixed in https://github.com/propublica/facebook-political-ads/commit/b65421c76e99dd8a41f1168fc20cccbddb8a67b3
