### ISSUE TITLE
Add "homepage_url" key to manifest.json?

### ISSUE THREAD

**Issue by pdehaan** [propublica/facebook-political-ads#80]
I installed the add-on in Firefox, but had no idea where to go for more information in about:addons. Not sure if you want to add a link to something like one of the following:

- https://projects.propublica.org/political-ad-collector/#firefox-instructions
- https://github.com/propublica/facebook-political-ads/

```js
"homepage_url": "https://github.com/propublica/facebook-political-ads/",
```

<img width="836" alt="add-ons_manager" src="https://user-images.githubusercontent.com/557895/46428487-f9352980-c6f8-11e8-9773-81449a952d3f.png">

**Comment by pdehaan** [comment]
Actually, I think my add-on just updated to 1.6.15 which has icons, homepage_url, and a much longer/better description.

![add-ons_managerfs](https://user-images.githubusercontent.com/557895/46428795-c3447500-c6f9-11e8-9a8a-1499b86b0f65.png)

**Comment by jeremybmerrill** [comment]
@pdehaan Thanks for your thoughts and I'm glad you find the longer description better :)

**Comment by jeremybmerrill** [comment]
Weird bug that the homepage_url wasn't working in v1.6.13...
