### ISSUE TITLE
Addon says I've categorized 0 ads - I think I've done at least 60

### ISSUE THREAD

**Issue by birdsarah** [propublica/facebook-political-ads#86]
Bit demoralizing. May have been better to not say anything at all

![screenshot from 2018-10-30 23-40-25](https://user-images.githubusercontent.com/1796208/47766585-6b1f7500-dc9d-11e8-9a3a-74a60582b78e.png)

* FF Nightly
* Linux
* FB Containers

Not sure what else would be useful info

**Comment by jeremybmerrill** [comment]
@birdsarah Heh, that definitely is a bug. Don't mean to be demoralizing. Thanks for letting me know. I'll try to get this out in the release I had planned for earlier this week (but obviously didn't manage to release.)

**Comment by jeremybmerrill** [comment]
I wouldn't be shocked if FB Containers was involved. I'm not sure how localStorage from an extension background page interacts with the FB Container thing.

**Comment by birdsarah** [comment]
I'm not seeing that bottom banner any more fwiw. Feel free to close this issue. Keep up the good work - I enjoyed the stories.

**Comment by jeremybmerrill** [comment]
Glad to hear!
